// src/components/API/Youglish.vue
<script>
import NullMessage from "@/components/NullMessage";
export default {
  data() {
    return {
      views: 0,
      curTrack: 0,
      totalTracks: 0,
      widget: null,
    };
  },
  components: {
    NullMessage,
  },
  props: {
    word: String,
  },
  watch: {
    word() {
      this.onYouglishAPIReady(this.word);
    },
  },
  created() {
    let tag = document.createElement("script");
    tag.src = "https://youglish.com/public/emb/widget.js";
    let firstScriptTag = document.getElementsByTagName("script")[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  },
  methods: {
    onYouglishAPIReady(word) {
      // var widget;
      this.widget = new YG.Widget("widget-1", {
        width: 450,
        height: 400,
        components: 9, //search box & caption
        events: {
          onFetchDone: this.onFetchDone,
          onVideoChange: this.onVideoChange,
          onCaptionConsumed: this.onCaptionConsumed,
        },
      });
      // 4. process the query
      this.widget.fetch(word, "english", "us");
    },
    // 5. The API will call this method when the search is done
    onFetchDone(event) {
      if (event.totalResult === 0) alert("No result found");
      else this.totalTracks = event.totalResult;
    },
    // 6. The API will call this method when switching to a new video.
    onVideoChange(event) {
      this.curTrack = event.trackNumber;
      this.views = 0;
    },
    // 7. The API will call this method when a caption is consumed.
    onCaptionConsumed(event) {
      if (++this.views < 1) this.widget.replay();
      else if (this.curTrack < this.totalTracks) this.widget.next();
    },
  },
};
</script>

<template>
  <div id="widget-1" @click="onYouglishAPIReady"></div>
  <div class="text" v-if="!word">
    <NullMessage />
  </div>
</template>

<style lang="scss">
#widget-1 {
  max-width: 500px;
  max-height: 400;
}
.null-message {
  h1 {
    font-size: 2.5rem;
    text-align: center;
    margin: 4rem auto;
  }
}

</style>

// components/app/youglish.tsx
/* eslint-disable */
// @ts-nocheck

import React, { useState, useEffect, useRef } from 'react';

type YouglishWidgetProps = {
  word: string;
  className: string;
  firstLetter: string;
};

function YouglishWidget({ word, className, firstLetter }: YouglishWidgetProps) {
  const isDev = process.env.NODE_ENV === 'development';

  if(isDev) return <div className={className}>Developing</div>;

  const widgetRef = useRef(null);
  const [views, setViews] = useState(0);
  const [curTrack, setCurTrack] = useState(0);
  const [totalTracks, setTotalTracks] = useState(0);
  let widget: { fetch: (arg0: any, arg1: string, arg2: string) => void; replay: () => void; next: () => void; }; // Widget instance

  const onYouglishAPIReady = (inputWord: string) => {
    widget = new YG.Widget(widgetRef.current, {
      width: 1200,
      height: 1200,
      components: 9,
      autoplay: true,
      autoReplay: true,
      autoNext: false,
      events: {
        onFetchDone,
        onVideoChange,
        onCaptionConsumed,
        nextVideo: () => {
          setViews(views + 1);
        },
        prevVideo: () => {
          setViews(views - 1);
        }
      },
    });

    widget.fetch(inputWord, 'english', 'us');
  };

  const onFetchDone = (event: { totalResult: React.SetStateAction<number>; }) => {
    if (event.totalResult === 0) {
      alert('No result found');
    } else {
      setTotalTracks(event.totalResult);
    }
  };

  const onVideoChange = (event: { trackNumber: React.SetStateAction<number>; }) => {
    setCurTrack(event.trackNumber);
    setViews(0);
  };

  const onCaptionConsumed = () => {
    if (views == 0) {
      widget.replay();
      setViews(views + 1);
    } else if (curTrack < totalTracks) {
      widget.next();
    } else {
      alert('All tracks have been played.');
    }
  };

  useEffect(() => {
    const scriptTag = document.createElement('script');
    scriptTag.src = 'https://youglish.com/public/emb/widget.js';
    const firstScriptTag = document.getElementsByTagName('script')[0];
    // @ts-ignore
    firstScriptTag.parentNode.insertBefore(scriptTag, firstScriptTag);

    setTimeout(() => {
      onYouglishAPIReady(firstLetter);
    }, 500);
  }, []);

  useEffect(() => {
    if (word) {
      onYouglishAPIReady(word);
    }
  }, [word]);

  return (
    <div className={className}>
      <div id="youglish-widget" ref={widgetRef}></div>
    </div>
  );
}

export default YouglishWidget;
